service: iot-serverless

plugins:
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true
  apiGatewayThrottling:
    maxRequestsPerSecond: 10
    maxConcurrentRequests: 5

provider:
  name: aws
  deploymentBucket:
    name: iot-automation
  profile: saml
  region: eu-west-2
  runtime: nodejs12.x
  environment:
    STAGE: ${opt:stage, "dev"}

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
