service: iot-serverless

plugins:
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true

provider:
  name: aws
  deploymentBucket:
    name: iot-automation
  profile: saml
  region: eu-west-2
  runtime: nodejs14.x
  stage: prod

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
